### ISSUE TITLE
Configuration Not working Store Level

### ISSUE THREAD

**Issue by prasad541-magento** [aligent/magento2-pinpayments#15]
1. Enable configuration from Store view scope(ex: online store view)
2. Disable configuration from Global scope
3. check payment method on store view (Online store as mentioned above) 
We are not able to see payment method.
 

Thanks,
Prasad

**Comment by moloughlin** [comment]
Hi Prasad,

Thanks for sharing that; I can confirm we're missing the scope parameter when retrieving config - we'll push a fix shortly.

Matt

**Comment by aligent-lturner** [comment]
Fixed by https://github.com/aligent/magento2-pinpayments/pull/16
